// src/data/storeData.js
export const stores1 = [
  {
    id: '1',
    name: 'kikis delivery shop',
    description: 'Fast and secure delivery service.',
    logo: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    rating: 4.8, // Added rating
    products:[
      {
        id: 1,
        name: "Wireless Headphones",
        description: "Noise-cancelling over-ear headphones with abcd",
        price: 129.99,
        image: "https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg",
      },
      {
        id: 2,
        name: "Smartwatch",
        description: "Fitness tracking smartwatch with heart rate monitor.",
        price: 99.99,
        image: "https://images-platform.99static.com//VArxVzYHdIiNcLp_auBaoqRtQ9g=/256x207:756x707/fit-in/500x500/99designs-contests-attachments/71/71434/attachment_71434832",
      },
      {
        id: 3,
        name: "Bluetooth Speaker",
        description: "Portable speaker with deep bass and waterproof design.",
        price: 59.99,
        image: "https://img.pikbest.com/png-images/20241027/anime-t-shirt-design_11011948.png!w700wp",
      },
      {
        id: 4,
        name: "Bluetooth Speaker",
        description: "Portable speaker with deep bass and waterproof design.",
        price: 9.99,
        image: "https://www.shutterstock.com/image-vector/vector-illustration-japan-comic-book-600nw-2331476417.jpg",
      },
      {
        id: 5,
        name: "Bluetooth Speaker",
        description: "Portable speaker with deep bass and waterproof design.",
        price: 5.99,
        image: "https://wallpapercat.com/w/full/7/1/4/1198692-3840x2160-desktop-4k-studio-ghibli-background-photo.jpg",
      },
      {
        id: 6,
        name: "Bluetooth Speaker",
        description: "Portable speaker with deep bass and waterproof design.",
        price: 0.99,
        image: "https://www.shutterstock.com/image-vector/vector-illustration-japan-comic-book-600nw-2331476417.jpg",
      },
    ]
  },
  {
    id: '2',
    name: 'sprited away',
    description: 'Trendy fashion and accessories for all seasons.',
    logo: 'https://helios-i.mashable.com/imagery/videos/04n02Re2bsEUfFRe8B6RmUM/hero-image.fill.size_1248x702.v1669371210.jpg',
    rating: 4.2, // Added rating
  },
  {
    id: '3',
    name: 'naruto',
    description: 'Thousands of books for all ages and interests.',
    logo: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2020%2F08%2Fnaruto-ichiraku-ramen-shop-lego-ideas-set-project-info-001.jpg',
    rating: 4.6, // Added rating
  },
  {
    id: '4',
    name: 'home heaven',
    description: 'Everything you need for a cozy and functional home.',
    logo: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    rating: 4.7, // Added rating
  },
  {
    id: '5',
    name: 'webb food',
    description: 'Supplements and gear for your fitness journey.',
    logo: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    rating: 4.3, // Added rating
  },
];
// src/data/storeData.js
export const stores = [
  {
    id: '1',
    name: 'Lumina',
    description: 'Illuminate your life with our curated collection of lighting solutions.',
    logo: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    rating: 4.8,
    shopBanner: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    shopPoster: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    products: [
      { id: 1, name: 'Aurora Floor Lamp', description: 'A sleek floor lamp that brings a warm glow to any room.', price: 89.99, image: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg' },
      { id: 2, name: 'Stellar Table Lamp', description: 'Compact and stylish, perfect for your bedside table.', price: 45.5, image: 'https://example.com/products/stellar-table-lamp.jpg' },
      { id: 3, name: 'Luxe Ceiling Light', description: 'A luxurious chandelier that transforms your space.', price: 199.99, image: 'https://example.com/products/luxe-ceiling-light.jpg' },
      { id: 4, name: 'Eclipse Wall Sconce', description: 'A modern sconce that adds elegance to any wall.', price: 60.0, image: 'https://example.com/products/eclipse-wall-sconce.jpg' },
      { id: 5, name: 'Neon LED Sign', description: 'Personalize your space with a custom neon sign.', price: 120.0, image: 'https://example.com/products/neon-led-sign.jpg' },
      { id: 6, name: 'Edison Bulb', description: 'Vintage-style light bulbs for that retro look.', price: 15.0, image: 'https://example.com/products/edison-bulb.jpg' },
      { id: 7, name: 'Solar Garden Lights', description: 'Environmentally friendly lighting for your garden.', price: 35.0, image: 'https://example.com/products/solar-garden-lights.jpg' },
      { id: 8, name: 'Smart Table Lamp', description: 'App-controlled lamp with adjustable brightness.', price: 99.99, image: 'https://example.com/products/smart-table-lamp.jpg' },
      { id: 9, name: 'Hanging Lanterns', description: 'Perfect for creating a cozy ambiance indoors or outdoors.', price: 40.0, image: 'https://example.com/products/hanging-lanterns.jpg' },
      { id: 10, name: 'Crystal Chandeliers', description: 'Elegant chandeliers to light up any luxurious room.', price: 299.99, image: 'https://example.com/products/crystal-chandeliers.jpg' },
      { id: 11, name: 'Swing Arm Desk Lamp', description: 'Adjustable desk lamp for the perfect workspace lighting.', price: 55.0, image: 'https://example.com/products/swing-arm-desk-lamp.jpg' },
      { id: 12, name: 'Compact LED Torch', description: 'Portable and powerful LED torch for outdoor adventures.', price: 20.0, image: 'https://example.com/products/compact-led-torch.jpg' },
      { id: 13, name: 'Retro Pendant Light', description: 'A throwback pendant light with a modern twist.', price: 75.0, image: 'https://example.com/products/retro-pendant-light.jpg' },
      { id: 14, name: 'Mini Desk Light', description: 'A small yet powerful light perfect for your desk.', price: 25.0, image: 'https://example.com/products/mini-desk-light.jpg' },
      { id: 15, name: 'Dimmable Wall Light', description: 'Wall-mounted light with dimming function for perfect ambiance.', price: 50.0, image: 'https://example.com/products/dimmable-wall-light.jpg' },
      { id: 16, name: 'Smart LED Strip Lights', description: 'Color-changing LED strips that you can control with an app.', price: 40.0, image: 'https://example.com/products/smart-led-strip-lights.jpg' },
      { id: 17, name: 'Table Lantern', description: 'A charming table lantern to add character to your decor.', price: 35.0, image: 'https://example.com/products/table-lantern.jpg' },
      { id: 18, name: 'Track Lighting System', description: 'Track lighting system for professional interior lighting.', price: 150.0, image: 'https://example.com/products/track-lighting-system.jpg' },
      { id: 19, name: 'Outdoor LED Floodlight', description: 'Bright and energy-efficient floodlight for outdoor areas.', price: 80.0, image: 'https://example.com/products/outdoor-led-floodlight.jpg' },
      { id: 20, name: 'Himalayan Salt Lamp', description: 'A soothing salt lamp with a natural glow for relaxation.', price: 40.0, image: 'https://example.com/products/himalayan-salt-lamp.jpg' },
      { id: 21, name: 'Vintage Edison Bulb', description: 'A large vintage-style Edison bulb that adds charm to any room.', price: 25.0, image: 'https://example.com/products/vintage-edison-bulb.jpg' },
      { id: 22, name: 'Industrial Wall Light', description: 'Industrial-style wall light for a rustic look.', price: 55.0, image: 'https://example.com/products/industrial-wall-light.jpg' },
      { id: 23, name: 'LED Night Light', description: 'A gentle night light that provides just enough light to sleep.', price: 15.0, image: 'https://example.com/products/led-night-light.jpg' },
      { id: 24, name: 'Pendant Ceiling Light', description: 'Stylish pendant light for the modern home.', price: 85.0, image: 'https://example.com/products/pendant-ceiling-light.jpg' },
      { id: 25, name: 'Smart Motion Sensor Light', description: 'A motion sensor light for automatic lighting activation.', price: 65.0, image: 'https://example.com/products/smart-motion-sensor-light.jpg' }
    ]
  },
  {
    id: '2',
    name: 'Nimbus',
    description: 'Experience comfort like never before with our premium bedding.',
    logo: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg',
    rating: 4.6,
    shopBanner: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg',
    shopPoster: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg',
    products: [
      { id: 1, name: 'CloudSoft Pillow', description: 'Ultra-soft pillow that adapts to your sleeping position.', price: 29.99, image: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg' },
      { id: 2, name: 'DreamWeave Sheets', description: 'Breathable sheets that keep you cool all night.', price: 59.99, image: 'https://example.com/products/dreamweave-sheets.jpg' },
      { id: 3, name: 'Serenity Mattress', description: 'Comfortable mattress designed for a restful night\'s sleep.', price: 399.99, image: 'https://example.com/products/serenity-mattress.jpg' },
      { id: 4, name: 'Cozy Blanket', description: 'Soft and warm blanket for chilly nights.', price: 49.99, image: 'https://example.com/products/cozy-blanket.jpg' },
      { id: 5, name: 'Memory Foam Mattress Topper', description: 'Additional layer of comfort to make your mattress even more comfortable.', price: 129.99, image: 'https://example.com/products/memory-foam-mattress-topper.jpg' },
      { id: 6, name: 'Cooling Gel Pillow', description: 'Gel-infused pillow to keep you cool during the night.', price: 89.99, image: 'https://example.com/products/cooling-gel-pillow.jpg' },
      { id: 7, name: 'Luxury Bedspread', description: 'An elegant bedspread for the ultimate bedroom upgrade.', price: 99.99, image: 'https://example.com/products/luxury-bedspread.jpg' },
      { id: 8, name: 'Bamboo Sheets', description: 'Sustainable and soft bamboo sheets that are gentle on your skin.', price: 79.99, image: 'https://example.com/products/bamboo-sheets.jpg' },
      { id: 9, name: 'Bed Pillows', description: 'Standard-sized pillows that provide support and comfort.', price: 35.00, image: 'https://example.com/products/bed-pillows.jpg' },
      { id: 10, name: 'Plush Robe', description: 'A plush robe to keep you cozy after a warm bath or shower.', price: 60.0, image: 'https://example.com/products/plush-robe.jpg' },
      { id: 11, name: 'Heated Blanket', description: 'Electric heated blanket for the ultimate warmth during winter.', price: 120.0, image: 'https://example.com/products/heated-blanket.jpg' },
      { id: 12, name: 'Satin Pillowcase', description: 'Silk pillowcases that help prevent hair breakage and wrinkles.', price: 20.0, image: 'https://example.com/products/satin-pillowcase.jpg' },
      { id: 13, name: 'Down Feather Pillow', description: 'Soft and supportive pillow filled with natural down feathers.', price: 45.0, image: 'https://example.com/products/down-feather-pillow.jpg' },
      { id: 14, name: 'Organic Cotton Mattress Protector', description: 'Natural cotton mattress protector to keep your bed fresh.', price: 40.0, image: 'https://example.com/products/organic-cotton-mattress-protector.jpg' },
      { id: 15, name: 'Adjustable Bed Frame', description: 'A bed frame that adjusts for maximum comfort and flexibility.', price: 299.99, image: 'https://example.com/products/adjustable-bed-frame.jpg' },
      { id: 16, name: 'Air Purifier', description: 'Air purifier for a clean and fresh sleeping environment.', price: 150.0, image: 'https://example.com/products/air-purifier.jpg' },
      { id: 17, name: 'Soft Fleece Blanket', description: 'Super soft fleece blanket perfect for colder climates.', price: 25.0, image: 'https://example.com/products/soft-fleece-blanket.jpg' },
      { id: 18, name: 'Cotton Comforter', description: 'A cotton comforter that is perfect for all seasons.', price: 70.0, image: 'https://example.com/products/cotton-comforter.jpg' },
      { id: 19, name: 'Bed Skirt', description: 'A decorative bed skirt to complete the look of your bed.', price: 15.0, image: 'https://example.com/products/bed-skirt.jpg' },
      { id: 20, name: 'Bamboo Mattress Pad', description: 'Mattress pad made from eco-friendly bamboo fabric.', price: 55.0, image: 'https://example.com/products/bamboo-mattress-pad.jpg' },
      { id: 21, name: 'Soft Cotton Throw', description: 'A soft and cozy cotton throw for your couch or bed.', price: 40.0, image: 'https://example.com/products/soft-cotton-throw.jpg' },
      { id: 22, name: 'Eco-Friendly Bed Sheets', description: 'Eco-friendly sheets made from organic cotton.', price: 60.0, image: 'https://example.com/products/eco-friendly-bed-sheets.jpg' },
      { id: 23, name: 'Luxury Mattress Protector', description: 'Mattress protector that provides waterproof protection and softness.', price: 45.0, image: 'https://example.com/products/luxury-mattress-protector.jpg' },
      { id: 24, name: 'Plush Comforter Set', description: 'A complete set of plush comforters for the ultimate bedroom comfort.', price: 150.0, image: 'https://example.com/products/plush-comforter-set.jpg' },
      { id: 25, name: 'Cooling Pillow Protector', description: 'Pillow protector designed to keep your pillow cool throughout the night.', price: 22.0, image: 'https://example.com/products/cooling-pillow-protector.jpg' }
    ]
  },
];

export const storeMap = {
  'Lumina': {
    id: '1',
    name: 'Lumina',
    description: 'Illuminate your life with our curated collection of lighting solutions.',
    logo: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg',
    rating: 4.8,
    shopBanner: ['https://img.freepik.com/premium-photo/clothes-closet-dress-rack_53876-245263.jpg'],
    shopPoster: 'https://img.freepik.com/free-photo/spring-wardrobe-switch-still-life_23-2150176694.jpg',
    products: [
      { id: 1, name: 'Aurora Floor Lamp', description: 'A sleek floor lamp that brings a warm glow to any room.', price: 89.99, image: 'https://i.pinimg.com/736x/eb/be/df/ebbedf009cd9dd4cc61cfb6702a9fb36.jpg' },
      { id: 2, name: 'Stellar Table Lamp', description: 'Compact and stylish, perfect for your bedside table.', price: 45.5, image: 'https://i.pinimg.com/736x/bc/44/8d/bc448d1b083b28fc1fe5d3035ae2294a.jpg' },
      { id: 3, name: 'Luxe Ceiling Light', description: 'A luxurious chandelier that transforms your space.', price: 199.99, image: 'https://i.pinimg.com/736x/f1/d5/a1/f1d5a19fad1345e554d50c81c3e5b681.jpg' },
      { id: 4, name: 'Eclipse Wall Sconce', description: 'A modern sconce that adds elegance to any wall.', price: 60.0, image: 'https://i.pinimg.com/736x/67/fe/c4/67fec4e9cd67c990fbd8d65c60205cc2.jpg' },
      { id: 5, name: 'Neon LED Sign', description: 'Personalize your space with a custom neon sign.', price: 120.0, image: 'https://i.pinimg.com/736x/57/c5/72/57c5721c856377718a342a054fc9500f.jpg' },
      { id: 6, name: 'Edison Bulb', description: 'Vintage-style light bulbs for that retro look.', price: 15.0, image: 'https://i.pinimg.com/474x/af/48/db/af48db64948ef9b7ae556b3e46dfce9d.jpg' },
      { id: 7, name: 'Solar Garden Lights', description: 'Environmentally friendly lighting for your garden.', price: 35.0, image: 'https://i.pinimg.com/736x/cc/a1/31/cca131705292f715acc060363bec6e21.jpg' },
      { id: 8, name: 'Smart Table Lamp', description: 'App-controlled lamp with adjustable brightness.', price: 99.99, image: 'hhttps://img.freepik.com/free-photo/still-life-hanging-bag_23-2151009066.jpg' },
      { id: 9, name: 'Hanging Lanterns', description: 'Perfect for creating a cozy ambiance indoors or outdoors.', price: 40.0, image: 'https://i.pinimg.com/736x/1c/04/b4/1c04b40211ffa3d6e87f4c1ba3454c0e.jpg' },
      { id: 10, name: 'Crystal Chandeliers', description: 'Elegant chandeliers to light up any luxurious room.', price: 299.99, image: 'https://example.com/products/crystal-chandeliers.jpg' },
      { id: 11, name: 'Swing Arm Desk Lamp', description: 'Adjustable desk lamp for the perfect workspace lighting.', price: 55.0, image: 'https://example.com/products/swing-arm-desk-lamp.jpg' },
      { id: 12, name: 'Compact LED Torch', description: 'Portable and powerful LED torch for outdoor adventures.', price: 20.0, image: 'https://example.com/products/compact-led-torch.jpg' },
      { id: 13, name: 'Retro Pendant Light', description: 'A throwback pendant light with a modern twist.', price: 75.0, image: 'https://example.com/products/retro-pendant-light.jpg' },
      { id: 14, name: 'Mini Desk Light', description: 'A small yet powerful light perfect for your desk.', price: 25.0, image: 'https://example.com/products/mini-desk-light.jpg' },
      { id: 15, name: 'Dimmable Wall Light', description: 'Wall-mounted light with dimming function for perfect ambiance.', price: 50.0, image: 'https://example.com/products/dimmable-wall-light.jpg' },
      { id: 16, name: 'Smart LED Strip Lights', description: 'Color-changing LED strips that you can control with an app.', price: 40.0, image: 'https://example.com/products/smart-led-strip-lights.jpg' },
      { id: 17, name: 'Table Lantern', description: 'A charming table lantern to add character to your decor.', price: 35.0, image: 'https://example.com/products/table-lantern.jpg' },
      { id: 18, name: 'Track Lighting System', description: 'Track lighting system for professional interior lighting.', price: 150.0, image: 'https://example.com/products/track-lighting-system.jpg' },
      { id: 19, name: 'Outdoor LED Floodlight', description: 'Bright and energy-efficient floodlight for outdoor areas.', price: 80.0, image: 'https://example.com/products/outdoor-led-floodlight.jpg' },
      { id: 20, name: 'Himalayan Salt Lamp', description: 'A soothing salt lamp with a natural glow for relaxation.', price: 40.0, image: 'https://example.com/products/himalayan-salt-lamp.jpg' },
      { id: 21, name: 'Vintage Edison Bulb', description: 'A large vintage-style Edison bulb that adds charm to any room.', price: 25.0, image: 'https://example.com/products/vintage-edison-bulb.jpg' },
      { id: 22, name: 'Industrial Wall Light', description: 'Industrial-style wall light for a rustic look.', price: 55.0, image: 'https://example.com/products/industrial-wall-light.jpg' },
      { id: 23, name: 'LED Night Light', description: 'A gentle night light that provides just enough light to sleep.', price: 15.0, image: 'https://example.com/products/led-night-light.jpg' },
      { id: 24, name: 'Pendant Ceiling Light', description: 'Stylish pendant light for the modern home.', price: 85.0, image: 'https://example.com/products/pendant-ceiling-light.jpg' },
      { id: 25, name: 'Smart Motion Sensor Light', description: 'A motion sensor light for automatic lighting activation.', price: 65.0, image: 'https://example.com/products/smart-motion-sensor-light.jpg' }
    ]
  },
  'Nimbus': {
    id: '2',
    name: 'Nimbus',
    description: 'Experience comfort like never before with our premium bedding.',
    logo: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg',
    rating: 4.6,
    shopBanner: ['https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg'],
    shopPoster: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg',
    products: [
      { id: 1, name: 'CloudSoft Pillow', description: 'Ultra-soft pillow that adapts to your sleeping position.', price: 29.99, image: 'https://i.pinimg.com/736x/3d/8a/2f/3d8a2fdd8cd19cc1ef65aa8993085a7b.jpg' },
      { id: 2, name: 'DreamWeave Sheets', description: 'Breathable sheets that keep you cool all night.', price: 59.99, image: 'https://example.com/products/dreamweave-sheets.jpg' },
      { id: 3, name: 'Serenity Mattress', description: 'Comfortable mattress designed for a restful night\'s sleep.', price: 399.99, image: 'https://example.com/products/serenity-mattress.jpg' },
      { id: 4, name: 'Cozy Blanket', description: 'Soft and warm blanket for chilly nights.', price: 49.99, image: 'https://example.com/products/cozy-blanket.jpg' },
      { id: 5, name: 'Memory Foam Mattress Topper', description: 'Additional layer of comfort to make your mattress even more comfortable.', price: 129.99, image: 'https://example.com/products/memory-foam-mattress-topper.jpg' },
      { id: 6, name: 'Cooling Gel Pillow', description: 'Gel-infused pillow to keep you cool during the night.', price: 89.99, image: 'https://example.com/products/cooling-gel-pillow.jpg' },
      { id: 7, name: 'Luxury Bedspread', description: 'An elegant bedspread for the ultimate bedroom upgrade.', price: 99.99, image: 'https://example.com/products/luxury-bedspread.jpg' },
      { id: 8, name: 'Bamboo Sheets', description: 'Sustainable and soft bamboo sheets that are gentle on your skin.', price: 79.99, image: 'https://example.com/products/bamboo-sheets.jpg' },
      { id: 9, name: 'Bed Pillows', description: 'Standard-sized pillows that provide support and comfort.', price: 35.00, image: 'https://example.com/products/bed-pillows.jpg' },
      { id: 10, name: 'Plush Robe', description: 'A plush robe to keep you cozy after a warm bath or shower.', price: 60.0, image: 'https://example.com/products/plush-robe.jpg' },
      { id: 11, name: 'Heated Blanket', description: 'Electric heated blanket for the ultimate warmth during winter.', price: 120.0, image: 'https://example.com/products/heated-blanket.jpg' },
      { id: 12, name: 'Satin Pillowcase', description: 'Silk pillowcases that help prevent hair breakage and wrinkles.', price: 20.0, image: 'https://example.com/products/satin-pillowcase.jpg' },
      { id: 13, name: 'Down Feather Pillow', description: 'Soft and supportive pillow filled with natural down feathers.', price: 45.0, image: 'https://example.com/products/down-feather-pillow.jpg' },
      { id: 14, name: 'Organic Cotton Mattress Protector', description: 'Natural cotton mattress protector to keep your bed fresh.', price: 40.0, image: 'https://example.com/products/organic-cotton-mattress-protector.jpg' },
      { id: 15, name: 'Adjustable Bed Frame', description: 'A bed frame that adjusts for maximum comfort and flexibility.', price: 299.99, image: 'https://example.com/products/adjustable-bed-frame.jpg' },
      { id: 16, name: 'Air Purifier', description: 'Air purifier for a clean and fresh sleeping environment.', price: 150.0, image: 'https://example.com/products/air-purifier.jpg' },
      { id: 17, name: 'Soft Fleece Blanket', description: 'Super soft fleece blanket perfect for colder climates.', price: 25.0, image: 'https://example.com/products/soft-fleece-blanket.jpg' },
      { id: 18, name: 'Cotton Comforter', description: 'A cotton comforter that is perfect for all seasons.', price: 70.0, image: 'https://example.com/products/cotton-comforter.jpg' },
      { id: 19, name: 'Bed Skirt', description: 'A decorative bed skirt to complete the look of your bed.', price: 15.0, image: 'https://example.com/products/bed-skirt.jpg' },
      { id: 20, name: 'Bamboo Mattress Pad', description: 'Mattress pad made from eco-friendly bamboo fabric.', price: 55.0, image: 'https://example.com/products/bamboo-mattress-pad.jpg' },
      { id: 21, name: 'Soft Cotton Throw', description: 'A soft and cozy cotton throw for your couch or bed.', price: 40.0, image: 'https://example.com/products/soft-cotton-throw.jpg' },
      { id: 22, name: 'Eco-Friendly Bed Sheets', description: 'Eco-friendly sheets made from organic cotton.', price: 60.0, image: 'https://example.com/products/eco-friendly-bed-sheets.jpg' },
      { id: 23, name: 'Luxury Mattress Protector', description: 'Mattress protector that provides waterproof protection and softness.', price: 45.0, image: 'https://example.com/products/luxury-mattress-protector.jpg' },
      { id: 24, name: 'Plush Comforter Set', description: 'A complete set of plush comforters for the ultimate bedroom comfort.', price: 150.0, image: 'https://example.com/products/plush-comforter-set.jpg' },
      { id: 25, name: 'Cooling Pillow Protector', description: 'Pillow protector designed to keep your pillow cool throughout the night.', price: 22.0, image: 'https://example.com/products/cooling-pillow-protector.jpg' }
    ]
  }
};
